### ISSUE TITLE
add keyboard shortcut for configurations

### ISSUE THREAD

**Issue by kalpaucjusz** [shamskv/EZVIDIA#1]
Hi,
I used the first version of this app, that created bat files for each configuration so I could easily assign key shortcuts to them. It would be nice if I could set keyboard shortcuts in the app because now I need to use two versions of it.

**Comment by shamskv** [comment]
Hi,
That was something I realized when building the new version but I didn't really know anyone (besides me) was using the app so I never tried to find a solution.

I'll try to quickly hack a new version with .bat generation and execution along with the GUI stuff. In the future I may try to integrate keyboard shortcuts into the program itself, but that seems a bit more complicated.

**Comment by kalpaucjusz** [comment]
I found you app on reddit and its the only one that make switching between my weird monitor setups easily, so thank you for that.

Bringing back bat files is fine too, more flexible than in-app shortcuts anyway.

**Comment by shamskv** [comment]
Hi there,
I just released a new version that allows you to generate the .bat files and run them. The batch files need to be in the same folder as the executable, but the program does not need to be running.

Please let me now if it works well. I'll wait for feedback before closing the issue.

**Comment by kalpaucjusz** [comment]
Hi,
Everything seems to be working. Thanks for adding that.
