### ISSUE TITLE
What executable?

### ISSUE THREAD

**Issue by jsunsawyer** [shamskv/EZVIDIA#3]
The documentation says: "Run the executable and look for a green notification icon in your task bar.", but I don't see an executable file.

I'd like to try this as a single audio/video switcher solution, but I'm not even sure how to run it!

Any help is appreciated. Thanks!

**Comment by shamskv** [comment]
Hi there,

The executables can be found in the [Releases Page](https://github.com/shamskv/EZVIDIA/releases). In this case I advise you to download the executable for the latest release (0.2.1).

Let me know if you have any other issue.
